version: "3"
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "3000:80"
        depends_on:
            - api
            - client
    postgres_admin:
        container_name: postgres_admin
        image: dpage/pgadmin4
        depends_on:
            - postgres
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
    postgres:
        container_name: postgres
        image: postgres:latest
        volumes:
            - /data/postgres:/data/postgres
        environment:
            - POSTGRES_USER=babacar
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=mydb
    redis:
        container_name: redis
        image: redis:latest
        command: redis-server
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
    api:
        container_name: api
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        depends_on:
            - postgres
            - redis
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=babacar
            - PG_HOST=postgres
            - PG_DATABASE=mydb
            - PG_PASSWORD=password
            - PG_PORT=5432
