name: Client CI/CD
on:
    push:
        branches:
            - main

env:
    TEST_IMAGE_NAME: horusen/multi-dep-client-test
    PROD_IMAGE_NAME: horusen/multi-dep-client-test

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build docker test image
              run: docker build -t $TEST_IMAGE_NAME -f ./client/Dockerfile.dev ./client
            - name: Run docker test image
              run: docker run $TEST_IMAGE_NAME npm run test:ci
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - name: Build docker image
              run: docker build -t $PROD_IMAGE_NAME ./client
            - name: Login to docker
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Push docker image
              run: docker push $PROD_IMAGE_NAME
